### ISSUE TITLE
Share buttons often fail

### ISSUE THREAD

**Issue by PaoloBova** [ideopunk/x-risk-tree#1]
Thanks for making this app. I really like that I can make my own trees using this tool. However, I found it very difficult to use the 'Share' buttons. A friend of mine who was also trying out the site encountered similar issues.

1. On Firefox + Windows 10 or Linux, clicking Share on the Home page or the Predict page throws the following error in the console: `Uncaught (in promise) ReferenceError: ClipboardItem is not defined`. No image is copied to clipboard.

![Possible Worlds Tree Screenshot 2022-09-06 164240](https://user-images.githubusercontent.com/25730504/188678472-f348a10f-19f2-47cc-b5cd-819a51f6f6f7.png)

2. On Chrome + Windows  10, clicking Share on the Home page or the Predict page can work for me under specific conditions. On clicking Share, Windows opens a menu to ask if I want to share it via Mail, Snip&Sketch, Feedback Hub, or One Note (this will differ for different users). Most of these options are mute and I don't use Mail on Windows, so I haven't tested that feature. If I choose Snip&Sketch, I can use the image file with that app, and the image is also saved to clipboard as expected. However, if I use one of the options which doesn't work or if I dismiss these options, I notice that the image is not saved to clipboard (even though the dialogue displays saying the image is copied - intuitively I'd expect to be able to paste it somewhere).  My preference would be for the image to always be saved to clipboard. This also seems like a good fallback in case users want to export/share their work but don't have a suitable app for that purpose.

**Comment by ideopunk** [comment]
Thanks for letting me know! I'll tackle this this week. The Firefox fix should come sooner. The Windows behavior is surprising, I assumed it would just copy to clipboard on desktop browsers.

**Comment by ideopunk** [comment]
The Windows issue is fixed, it should default to writing to the clipboard. Firefox proved to be trickier because it doesn't yet support `navigator.clipboard.write` outside of browser extensions, and I couldn't find a way for the legacy method (`execCommand('copy')`) to actually copy an image and not its alt text. So for now I've just removed the share button from Firefox so as to not be misleading. Until FF properly supports writing images to the clipboard, its native screenshot function will have to do, unfortunately.
